require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache_rails_dir
  MaxFilesInCache: 4000

#################### Style ###########################

##################### Metrics ##################################

##################### Rails ##################################

Rails:
  Enabled: true

##################### RSpec ##################################

FactoryBot/AttributeDefinedStatically:
  Enabled: true


RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/ability/*"
