# Inherit style from another configuration
inherit_from: .rubocop_todo.yml

# Apply rule to all cops
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'


#################### Metrics ###############################

# Avoid deep blocks nesting
Metrics/BlockNesting:
  Max: 4

# Avoid writing classes that are more than 300 lines
Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'app/models/conference.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/conference_spec.rb'
    - 'spec/features/ability_spec.rb'
    - 'spec/models/ability_spec.rb'
    - 'spec/models/admin_ability_spec.rb'
