<%
  encoding = 'unicode'
  if ENV['OSEM_DB_ADAPTER'] == 'mysql2'
    encoding = 'utf8'
  end

  development_database = ENV['OSEM_DB_NAME'] || 'osem_development'
  test_database = ENV['OSEM_DB_NAME'] || 'osem_test'
  if ENV['OSEM_DB_ADAPTER'] == 'sqlite3'
    development_database = "db/#{development_database}.sqlite3"
    test_database = "db/#{test_database}.sqlite3"
  end
%>


default: &default
  adapter: <%= ENV['OSEM_DB_ADAPTER'] || 'postgresql' %>
  encoding: <%= encoding %>
  host: <%= ENV['OSEM_DB_HOST'] || 'database' %>
  port: <%= ENV['OSEM_DB_PORT'] || '5432'  %>
  username: <%= ENV['OSEM_DB_USER'] || 'postgres' %>
  password: <%= ENV['OSEM_DB_PASSWORD'] || 'mysecretpassword' %>
  database: <%= ENV['OSEM_DB_NAME'] || 'postgres' %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= development_database %>

# Warning: The database defined as "test" will be erased and
# re-generated when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= test_database %>

production:
  <<: *default
